const express = require('express');
const router = express.Router();
const controller = require('../controllers/receipt.controller');
const upload = require('../config/multer');
router.post('/api/phieu-nhap', upload.any(), controller.post__api_phieu_nhap);
router.get('/api/hoa-don/:userId', controller.get__api_hoa_don_userId);
router.get('/api/phieu-nhap', controller.get__api_phieu_nhap);
router.put('/api/phieu-nhap/:id/staff-cap-nhat', controller.put__api_phieu_nhap_id_staff_cap_nhat);
router.put('/api/phieu-nhap/:id/admin-cap-nhat', controller.put__api_phieu_nhap_id_admin_cap_nhat);
router.put('/api/phieu-nhap/:id/hoan-tat', controller.put__api_phieu_nhap_id_hoan_tat);
router.get('/api/phieu-nhap/:id/san-pham', controller.get__api_phieu_nhap_id_san_pham);
router.post('/api/phieu-xuat', upload.any(), controller.post__api_phieu_xuat);
router.get('/api/phieu-xuat', controller.get__api_phieu_xuat);
router.get('/api/phieu-xuat/:id/san-pham', controller.get__api_phieu_xuat_id_san_pham);
router.put('/api/phieu-xuat/:id/admin-cap-nhat', controller.put__api_phieu_xuat_id_admin_cap_nhat);
router.post('/api/phieu-xuat/xac-nhan-xuat-kho/:id', controller.post__api_phieu_xuat_xac_nhan_xuat_kho_id);
router.put('/api/phieu-nhap/:id/xuat-hoa-don', controller.put__api_phieu_nhap_id_xuat_hoa_don);
router.put('/api/phieu-xuat/:id/xuat-hoa-don', controller.put__api_phieu_xuat_id_xuat_hoa_don);
router.get('/api/hoa-don', controller.get__api_hoa_don);
router.get('/api/tong-phieu-nhap-xuat', controller.get__api_tong_phieu_nhap_xuat);
router.put('/api/phieu-nhap-kho/:id/huy', controller.put__api_phieu_nhap_kho_id_huy);
router.put('/api/phieu-xuat-kho/:id/huy', controller.put__api_phieu_xuat_kho_id_huy);
module.exports = router;
