const express = require('express');
const router = express.Router();
const controller = require('../controllers/warehouse.controller');
router.get('/api/khu-vuc', controller.get__api_khu_vuc);
router.get('/api/khu-vuc', controller.get__api_khu_vuc);
router.get('/api/log-tru-hang/:productCode', controller.get__api_log_tru_hang_productCode);
router.get('/api/khu-vuc', controller.get__api_khu_vuc);
router.get('/api/suppliers/by-product/:product_code', controller.get__api_suppliers_by_product_product_code);
router.get('/api/suppliers/by-khu-vuc/:khuvuc_id', controller.get__api_suppliers_by_khu_vuc_khuvuc_id);
router.get('/api/suppliers/recent', controller.get__api_suppliers_recent);
router.get('/api/suppliers/detail-by-name/:supplier_name', controller.get__api_suppliers_detail_by_name_supplier_name);
router.get('/api/suppliers/by-product-name/:product_name', controller.get__api_suppliers_by_product_name_product_name);
router.post('/api/kiem-ke/create', controller.post__api_kiem_ke_create);
router.get('/api/kiem-ke/dot/:dotId', controller.get__api_kiem_ke_dot_dotId);
router.post('/api/kiem-ke/unmark', controller.post__api_kiem_ke_unmark);
router.post('/api/kiem-ke/submit', controller.post__api_kiem_ke_submit);
router.post('/api/kiem-ke/tao-dot', controller.post__api_kiem_ke_tao_dot);
router.post('/api/kiem-ke/gan-san-pham-vao-dot', controller.post__api_kiem_ke_gan_san_pham_vao_dot);
router.get('/api/kiem-ke/dot/:dotId/san-pham', controller.get__api_kiem_ke_dot_dotId_san_pham);
router.post('/api/kiem-ke/cap-nhat-chi-tiet', controller.post__api_kiem_ke_cap_nhat_chi_tiet);
router.get('/api/kiem-ke/danh-sach-dot', controller.get__api_kiem_ke_danh_sach_dot);
router.get('/api/kiem-ke/dot-dang-kiem', controller.get__api_kiem_ke_dot_dang_kiem);
router.get('/api/kiem-ke/bao-cao-dot/:dotId', controller.get__api_kiem_ke_bao_cao_dot_dotId);
router.post('/api/kiem-ke/reset-san-pham', controller.post__api_kiem_ke_reset_san_pham);
router.post('/api/kiem-ke/xoa-san-pham-khoi-dot', controller.post__api_kiem_ke_xoa_san_pham_khoi_dot);
router.post('/api/kiem-ke/xoa-nhieu-san-pham', controller.post__api_kiem_ke_xoa_nhieu_san_pham);
router.delete('/api/kiem-ke/huy-dot/:dotId', controller.delete__api_kiem_ke_huy_dot_dotId);
router.delete('/api/kiem-ke/huy-dot/:dotId', controller.delete__api_kiem_ke_huy_dot_dotId);
router.get('/api/kiem-ke/chua-kiem', controller.get__api_kiem_ke_chua_kiem);
router.put('/api/kiem-ke/dot/:id/ket-thuc', controller.put__api_kiem_ke_dot_id_ket_thuc);
router.get('/api/vi-tri-con-trong', controller.get__api_vi_tri_con_trong);
router.get('/api/thong-ke', controller.get__api_thong_ke);
router.get('/api/khu_vuc_suc_chua', controller.get__api_khu_vuc_suc_chua);
router.get('/api/doanh_thu', controller.get__api_doanh_thu);
router.get('/api/nha_cung_cap', controller.get__api_nha_cung_cap);
router.get('/api/xuat-excel/kiem-ke/:dotId', controller.get__api_xuat_excel_kiem_ke_dotId);
router.get('/api/tong_gia_tri_ton_kho', controller.get__api_tong_gia_tri_ton_kho);
module.exports = router;
